import React from 'react';
import './css/App.scss';
import 'bootstrap/dist/css/bootstrap.min.css';
import {useState} from 'react'

/*Routing*/
import { Routes, Route } from 'react-router-dom';
/* Global Header and Footer */
import Header from './components/header.js';
import Footer from './components/footer.js';
/* Main Page Components */
import Home from './components/home/home'
/* Events components */
import Event from './components/events/event';
import EventsList from './components/events/eventList';
import AddEvent from './components/events/addEvent';
import DeleteEvent from './components/events/delete';
/* Trips components */
import Tripslist from './components/trips/tripsList';
import Trip from './components/trips/trip';
import AddTrip from './components/trips/addTrip';
import DeleteTrip from './components/trips/delete';
/* Motorcycles Components */
import Motorcycle from './components/motorcycles/motorcycle';
import MotorcyclesList from './components/motorcycles/motorcycleList';
import AddMotorcycle from './components/motorcycles/addMotorcycle';
import DeleteMotorcycle from './components/motorcycles/delete';
/* Riders Components */
import Rider from './components/riders/rider';
import RidersList from './components/riders/riderList';
import AddRider from './components/riders/addRider';
import DeleteRider from './components/riders/delete';
/* 404 error component */
import NotFound from './components/notFound';

function App() {

  const[trip, setTrip] = useState(null)
  const[event, setEvent] = useState(null)
  const[rider, setRider] = useState(null)
  const[motorcycle, setMotorcycle] = useState(null)

  const editTrip = (trip) => {
    setTrip(trip)
  }

  const editEvent = (event) => {
    setEvent(event)
  }

  const editRider = (rider) => {
    setRider(rider)
  }

  const editMotorcycle = (motorcycle) => {
    setMotorcycle(motorcycle)
  }

  return (
    <div className="App">
      <Header/>
      {/* The main content is generated by the browser router */}
      <Routes>
          <Route path='/' element={<Home/>}/>
          <Route path='/events' element={<EventsList editEvent = {editEvent}/>}/>
          <Route path='/events/:id' element={<Event editEvent = {editEvent}/>}/>
          <Route path='/events/addEvent' element={<AddEvent event = {event}/>}/>
          <Route path='/events/delete' element={<DeleteEvent event = {event}/>}/>
          <Route path='/trips' element={<Tripslist editTrip = {editTrip}/>}/>
          <Route path='/trips/:id' element={<Trip editTrip = {editTrip}/>}/>
          <Route path='/trips/addTrip' element={<AddTrip trip = {trip}/>}/>
          <Route path='/trips/delete' element={<DeleteTrip trip = {trip}/>}/>
          <Route path='/motorcycles' element={<MotorcyclesList editMotorcycle = {editMotorcycle}/>}/>
          <Route path='/motorcycles/:id' element={<Motorcycle editMotorcycle = {editMotorcycle}/>}/>
          <Route path='/motorcycles/addMotorcycle' element={<AddMotorcycle motorcycle = {motorcycle}/>}/>
          <Route path='/motorcycles/delete' element={<DeleteMotorcycle motorcycle = {motorcycle}/>}/>
          <Route path='/riders' element={<RidersList editRider = {editRider}/>}/>
          <Route path='/riders/:id' element={<Rider editRider = {editRider}/>}/>
          <Route path='/riders/addRider' element={<AddRider rider = {rider}/>}/>
          <Route path='/riders/delete' element={<DeleteRider rider = {rider}/>}/>
          <Route path='/*' element={<NotFound/>}/>
      </Routes>
      <Footer/>
    </div>
  );
}

export default App;