import React from 'react';
import logo from './logo.svg';
import './App.css';
/*Routing*/
import { Routes, Route } from 'react-router-dom';
/* Global Header and Footer */
import Header from './components/header.js';
import Footer from './components/footer.js';
/* Main Page Components */
import Home from './components/home/home'
import Events from './components/events/events';
import Trips from './components/trips/trips';
import Motorcycles from './components/motorcycles/motorcycles';
import Riders from './components/riders/riders';
import NotFound from './components/notFound';


function App() {
  return (
    <div className="App">
      <Header/>
      {/* The main content is generated by the browser router */}
    <Routes>
        <Route path='/' element={<Home/>}/>
        <Route path='/events' element={<Events/>}/>
        <Route path='/trips' element={<Trips/>}/>
        <Route path='/motorcycles' element={<Motorcycles/>}/>
        <Route path='/riders' element={<Riders/>}/>
        <Route path='/*' element={<NotFound/>}/>
    </Routes>
      <Footer/>
    </div>
  );
}

export default App;
